config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks",
    registrations: "registrations",
    invitations: "invitations",
    passwords: "passwords",
    confirmations: "confirmations"
  }

  devise_scope :user do
    get "/enter", to: "registrations#new", as: :sign_up
    get "/confirm-email", to: "confirmations#new"
    delete "/sign_out", to: "devise/sessions#destroy"
  end

  get "/r/mobile", to: "deep_links#mobile"
  get "/.well-known/apple-app-site-association", to: "deep_links#aasa"

  scope "(/locale/:locale)", defaults: { locale: nil } do
    get "/locale/:locale", to: "stories#index"

    draw :admin

    constraints(->(_req) { Listing.feature_enabled? }) do
      draw :listing
    end

    namespace :stories, defaults: { format: "json" } do
      resource :feed, only: [:show] do
        resource :pinned_article, only: %w[show update destroy]

        get ":timeframe", to: "feeds#show", as: :timeframe
      end
    end

    namespace :api, defaults: { format: "json" } do
      scope module: :v1, constraints: ApiConstraints.new(version: 1, default: false) do
        put "/users/:id/suspend", to: "users#suspend", as: :user_suspend
        put "/articles/:id/unpublish", to: "articles#unpublish", as: :article_unpublish
        put "/users/:id/unpublish", to: "users#unpublish", as: :user_unpublish

        post "/reactions", to: "reactions#create"
        post "/reactions/toggle", to: "reactions#toggle"

        draw :api
      end

      scope module: :v0, constraints: ApiConstraints.new(version: 0, default: true) do
        draw :api
      end
    end

    namespace :notifications do
      resources :counts, only: [:index]
      resources :reads, only: [:create]
    end

    namespace :incoming_webhooks do
      get "/mailchimp/:secret/unsubscribe", to: "mailchimp_unsubscribes#index", as: :mailchimp_unsubscribe_check
      post "/mailchimp/:secret/unsubscribe", to: "mailchimp_unsubscribes#create", as: :mailchimp_unsubscribe
    end

    resources :messages, only: [:create]
    resources :articles, only: %i[update create destroy] do
      patch "/admin_unpublish", to: "articles#admin_unpublish"
      patch "/admin_featured_toggle", to: "articles#admin_featured_toggle"
    end
    resources :article_mutes, only: %i[update]
    resources :comments, only: %i[create update destroy] do
      patch "/hide", to: "comments#hide"
      patch "/unhide", to: "comments#unhide"
      patch "/admin_delete", to: "comments#admin_delete"
      collection do
        post "/moderator_create", to: "comments#moderator_create"
      end
    end
    resources :comment_mutes, only: %i[update]
    resources :users, only: %i[index], defaults: { format: :json } do # internal API
      collection do
        resources :devices, only: %i[create destroy]
      end
    end
    namespace :users do
      resource :settings, only: %i[update]
      resource :notification_settings, only: %i[update]
    end
    resources :users, only: %i[update]
    resources :reactions, only: %i[index create]
    resources :response_templates, only: %i[index create edit update destroy]
    resources :feedback_messages, only: %i[index create]
    resources :organizations, only: %i[update create destroy]
    resources :follows, only: %i[show create] do
      collection do
        get "/bulk_show", to: "follows#bulk_show"
        patch "/bulk_update", to: "follows#bulk_update"
      end
    end
    resources :image_uploads, only: [:create]
    resources :notifications, only: [:index]
    resources :tags, only: [:index] do
      collection do
        get "/onboarding", to: "tags#onboarding"
        get "/suggest", to: "tags#suggest", defaults: { format: :json }
        get "/bulk", to: "tags#bulk", defaults: { format: :json }
      end
    end
    resources :stripe_active_cards, only: %i[create update destroy]
    resources :github_repos, only: %i[index] do
      collection do
        post "/update_or_create", to: "github_repos#update_or_create"
      end
    end
    resources :videos, only: %i[index create new]
    resources :video_states, only: [:create]
    resources :twilio_tokens, only: [:show]
    resources :tag_adjustments, only: %i[create destroy]
    resources :rating_votes, only: [:create]
    resources :page_views, only: %i[create update]
    resources :credits, only: %i[index new create] do
      get "purchase", on: :collection, to: "credits#new"
    end
    resources :reading_list_items, only: [:update]
    resources :poll_votes, only: %i[show create]
    resources :poll_skips, only: [:create]
    resources :profile_pins, only: %i[create update]
    resources :display_ad_events, only: [:create]
    resources :badges, only: [:index]
    resources :user_blocks, param: :blocked_id, only: %i[show create destroy]
    resources :podcasts, only: %i[new create]
    resources :article_approvals, only: %i[create]
    resources :sidebars, only: %i[show]
    resources :profile_preview_cards, only: %i[show]
    resources :user_subscriptions, only: %i[create] do
      collection do
        get "/subscribed", action: "subscribed"
      end
    end
    namespace :followings, defaults: { format: :json } do
      get :users
      get :tags
      get :organizations
      get :podcasts
    end

    scope module: "users" do
      resource :onboarding, only: %i[show update]
      patch "/onboarding_checkbox_update", to: "onboardings#onboarding_checkbox_update"
    end

    resources :profiles, only: %i[update]
    resources :profile_field_groups, only: %i[index], defaults: { format: :json }

    resources :liquid_tags, only: %i[index], defaults: { format: :json }

    resources :discussion_locks, only: %i[create destroy]

    get "/verify_email_ownership", to: "email_authorizations#verify", as: :verify_email_authorizations
    get "/search/tags", to: "search#tags"
    get "/search/usernames", to: "search#usernames"
    get "/search/feed_content", to: "search#feed_content"
    get "/search/reactions", to: "search#reactions"
    get "/notifications/:filter", to: "notifications#index", as: :notifications_filter
    get "/notifications/:filter/:org_id", to: "notifications#index", as: :notifications_filter_org
    get "/notification_subscriptions/:notifiable_type/:notifiable_id", to: "notification_subscriptions#show"
    post "/notification_subscriptions/:notifiable_type/:notifiable_id", to: "notification_subscriptions#upsert"
    patch "/onboarding_notifications_checkbox_update",
          to: "users/notification_settings#onboarding_notifications_checkbox_update"
    get "email_subscriptions/unsubscribe"

    get "/internal", to: redirect("/admin")
    get "/internal/:path", to: redirect("/admin/%{path}")

    get "/social_previews/article/:id", to: "social_previews#article", as: :article_social_preview

    get "/async_info/base_data", controller: "async_info#base_data", defaults: { format: :json }

    post "users/join_org", to: "users#join_org"
    post "users/leave_org/:organization_id", to: "users#leave_org", as: :users_leave_org
    post "users/add_org_admin", to: "users#add_org_admin"
    post "users/remove_org_admin", to: "users#remove_org_admin"
    post "users/remove_from_org", to: "users#remove_from_org"
    delete "users/remove_identity", to: "users#remove_identity"
    post "users/request_destroy", to: "users#request_destroy", as: :user_request_destroy
    get "users/confirm_destroy/:token", to: "users#confirm_destroy", as: :user_confirm_destroy
    delete "users/full_delete", to: "users#full_delete", as: :user_full_delete
    post "organizations/generate_new_secret", to: "organizations#generate_new_secret"
    post "users/api_secrets", to: "api_secrets#create", as: :users_api_secrets
    delete "users/api_secrets/:id", to: "api_secrets#destroy", as: :users_api_secret
    post "users/update_password", to: "users#update_password", as: :user_update_password

    get "/robots.:format", to: "pages#robots"
    get "/api", to: redirect("https://developers.forem.com/api")
    get "/privacy", to: "pages#privacy"
    get "/terms", to: "pages#terms"
    get "/contact", to: "pages#contact"
    get "/code-of-conduct", to: "pages#code_of_conduct"
    get "/report-abuse", to: "pages#report_abuse"
    get "/welcome", to: "pages#welcome"
    get "/challenge", to: "pages#challenge"
    get "/checkin", to: "pages#checkin"
    get "/💸", to: redirect("t/hiring")
    get "/survey", to: redirect("https://dev.to/ben/final-thoughts-on-the-state-of-the-web-survey-44nn")
    get "/search", to: "stories/articles_search#index"
    post "articles/preview", to: "articles#preview"
    post "comments/preview", to: "comments#preview"

    get "/about", to: "pages#about"
    get "/security", to: "pages#bounty"
    get "/community-moderation", to: "pages#community_moderation"
    get "/faq", to: "pages#faq"
    get "/page/post-a-job", to: "pages#post_a_job"
    get "/tag-moderation", to: "pages#tag_moderation"

    get "/mod", to: "moderations#index", as: :mod
    get "/mod/:tag", to: "moderations#index"

    post "/fallback_activity_recorder", to: "ga_events#create"

    get "/page/:slug", to: "pages#show"

    scope "p" do
      pages_actions = %w[welcome editor_guide publishing_from_rss_guide markdown_basics].freeze
      pages_actions.each do |action|
        get action, action: action, controller: "pages"
      end
    end

    get "/settings/integrations", to: redirect("/settings/extensions")
    get "/settings/misc", to: redirect("/settings")
    get "/settings/publishing-from-rss", to: redirect("/settings/extensions")
    get "/settings/ux", to: redirect("/settings/customization")

    get "/settings/(:tab)", to: "users#edit", as: :user_settings
    get "/settings/:tab/:org_id", to: "users#edit", constraints: { tab: /organization/ }
    get "/settings/:tab/:id", to: "users#edit", constraints: { tab: /response-templates/ }
    get "/signout_confirm", to: "users#signout_confirm"
    get "/dashboard", to: "dashboards#show"

app/controllers/notifications/counts_controller.rb
module Notifications
  class CountsController < ApplicationController
    def index
      count = current_user ? current_user.notifications.unread.count : 0
      render plain: count.to_s
    end
  end
end

app/controllers/notifications/reads_controller.rb
module Notifications
  class ReadsController < ApplicationController
    def create
      render plain: "" && return unless current_user

      current_user.notifications.unread.update_all(read: true)
      current_user.touch(:last_notification_activity)

      if params[:org_id] && current_user.org_member?(params[:org_id])
        org = Organization.find_by(id: params[:org_id])
        org.notifications.unread.update_all(read: true)
      end

      render plain: "read"
    end
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  # rubocop:disable Metrics/CyclomaticComplexity
  # rubocop:disable Metrics/PerceivedComplexity
  # No authorization required because we provide authentication on notifications page
  def index
    return unless user_signed_in?

    @user = user_to_view

    @initial_page_size = 8

    # NOTE: this controller is using offset based pagination by assuming that
    # the id of the last notification also corresponds to the newest `notified_at`
    # this might not be forever true but it's good enough for now
    if params[:offset]
      num = 30
      notified_at_offset = Notification.find(params[:offset])&.notified_at
    else
      num = @initial_page_size
    end

    @notifications = if (params[:org_id].present? || params[:filter] == "org") && allowed_user?
                       organization_notifications
                     elsif params[:org_id].blank? && params[:filter].present?
                       filtered_notifications
                     else
                       @user.notifications
                     end

    @notifications = @notifications.order(notified_at: :desc)

    # if offset based pagination is invoked by the frontend code, we filter out all earlier ones
    @notifications = @notifications.where("notified_at < ?", notified_at_offset) if notified_at_offset

    @notifications = @notifications.limit(num)

    @notifications = NotificationDecorator.decorate_collection(@notifications)

    @last_user_reaction = @user.reactions.last&.id
    @last_user_comment = @user.comments.last&.id

    @organizations = @user.member_organizations if @user.organizations
    @selected_organization = Organization.find(params[:org_id]) if params[:org_id].present?

    # The first call, the one coming from the browser URL bar will render the "index" view, which renders
    # the first few notifications. After that the JS frontend code (see `initNotification.js`)
    # will call this action again by sending the offset id for the last known notifications, the result
    # will be the partial rendering of only the list of notifications that will be attached to the DOM by JS
    if notified_at_offset
      render partial: "notifications_list"
    else
      # [@jeremyf] I added an explicit render.  Before adding the explicit render, we relied on the
      # implicit render cycle of Rails.  Which is fine, but it's very disarming to read `render
      # partial: "notifications_list" if notified_at_offset` as the last line of the method.
      #
      # My hope is that this explicit render removes at least one future head scratch.
      render "index"
    end
  end
  # rubocop:enable Metrics/CyclomaticComplexity
  # rubocop:enable Metrics/PerceivedComplexity

  private

  def user_to_view
    if params[:username] && current_user.super_admin?
      User.find_by(username: params[:username])
    else
      current_user
    end
  end

  def filtered_notifications
    if params[:filter].to_s.casecmp("posts").zero?
      @user.notifications.for_published_articles
    elsif params[:filter].to_s.casecmp("comments").zero?
      @user.notifications.for_comments.or(@user.notifications.for_mentions)
    else
      @user.notifications
    end
  end

  def organization_notifications
    org_id = params[:org_id]

    if params[:filter].to_s.casecmp("comments").zero?
      Notification.for_organization_comments(org_id).or(Notification.for_organization_mentions(org_id))
    else
      Notification.for_organization(org_id)
    end
  end

  def allowed_user?
    @user.org_member?(params[:org_id]) || @user.super_admin?
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  REACTION_IMAGES = {
    "like" => "heart-filled.svg",
    "unicorn" => "unicorn-filled.svg",
    "hands" => "twemoji/hands.svg",
    "thinking" => "twemoji/thinking.svg",
    "readinglist" => "save-filled.svg",
    "thumbsdown" => "twemoji/thumb-down.svg",
    "vomit" => "twemoji/suspicious.svg"
  }.freeze

  def reaction_image(category)
    REACTION_IMAGES[category]
  end

  def message_user_acted_maybe_org(data, action, if_org: "")
    key_to_link = ->(key) { link_to(data[key]["name"], data[key]["path"], class: "crayons-link fw-bold") }
    if if_org.present?
      I18n.t(
        action,
        user: key_to_link.call("user"),
        if_org: data["organization"] ? I18n.t(if_org, org: key_to_link.call("organization")) : "",
      )
    else
      I18n.t(action, user: key_to_link.call("user"))
    end.html_safe # rubocop:disable Rails/OutputSafety
  end
end

app/views/notifications/_aggregated_reactions.html.erb
<%# TODO: change to map of IDs %>
<% actors = siblings.map { |n| n["user"] }.uniq %>
<% reactable_data = notification.json_data["reaction"]["reactable"] %>

<div class="relative shrink-0 self-start">
  <% if actors.size == 1 %>
    <a href="<%= actors.first["path"] %>" class="crayons-avatar crayons-avatar--l m:crayons-avatar--xl" aria-hidden="true" tabindex="-1">
      <img src="<%= actors.first["profile_image_90"] %>" class="crayons-avatar__image" alt="link to <%= actors.first["username"] %>'s profile" width="48" height="48">
    </a>
  <% else %>
    <a href="<%= actors.first["path"] %>" class="crayons-avatar crayons-avatar--l mr-4" aria-hidden="true" tabindex="-1">
      <img src="<%= actors.first["profile_image_90"] %>" class="crayons-avatar__image" alt="link to <%= actors.first["username"] %>'s profile" width="48" height="48">
    </a>
    <a href="<%= actors.first["path"] %>" class="crayons-avatar crayons-avatar--l absolute -right-1 -bottom-3 border-solid border-2 border-base-inverted" aria-hidden="true" tabindex="-1">
      <img src="<%= actors.last["profile_image_90"] %>" class="crayons-avatar__image" alt="link to <%= actors.last["username"] %>'s profile" width="48" height="48">
    </a>
  <% end %>
</div>

<div class="notification__content pt-2">
  <% reaction_categories = siblings.map { |n| n["category"] } %>
  <%= t("views.notifications.reacted.verb_html",
        count: actors.size,
        start: tag("span", { class: %w[inline-block py-1] }, true), # rubocop:disable Rails/ContentTag
        actors: if actors.size == 1
                  link_to actors.first["name"], actors.first["path"], class: "crayons-link fw-bold"
                elsif actors.size == 2
                  t("views.notifications.reacted.and_html",
                    first: link_to(actors.first["name"], actors.first["path"], class: "crayons-link fw-bold"),
                    last: link_to(actors.last["name"], actors.last["path"], class: "crayons-link fw-bold"))
                elsif actors.size > 1
                  t("views.notifications.reacted.and_other_html",
                    first: link_to(actors.first["name"], actors.first["path"], class: "crayons-link fw-bold"),
                    count: actors.size - 1)
                end,
        # your article/comment or the actual title of the article/comment
        title: link_to(reactable_data["title"].blank? ? t("views.notifications.reacted.your.#{reactable_data['class']['name'].downcase}") : h(reactable_data["title"]), reactable_data["path"], class: "crayons-link fw-bold"),
        end: "</span>".html_safe,
        reactions: safe_join(
          reaction_categories.filter_map do |cat|
            image_path = reaction_image(cat)
            if image_path.present?
              "<span class='crayons-hover-tooltip inline-block' data-tooltip='#{t("views.reactions.category.#{cat}")}'>
                #{crayons_icon_tag(image_path, class: "reaction-image mx-1 my-1 reaction-icon--#{cat}")}
              </span>".html_safe
            end
          end, "\n"
        )) %>
</div>

app/views/notifications/_article.html.erb
<div class="crayons-card notification">
  <% if notification.action == "Reaction" %>
    <%= render "reaction", notification: notification %>
  <% elsif notification.action.include? "Milestone" %>
    <%= render "milestone", notification: notification %>
  <% else %>
    <% json_data = notification.json_data %>
    <%= render "notifications/shared/profile_pic", json_data: json_data %>

    <div class="notification__content">
      <header class="mb-4">
        <h2 class="fs-base fw-normal">
          <%= message_user_acted_maybe_org(json_data, "views.notifications.new_post.verb_html", if_org: "views.notifications.new_post.if_org_html") %>
        </h2>
        <p class="lh-tight"><small class="fs-s color-base-60"><%= time_ago_in_words json_data["article"]["published_at"], scope: :"datetime.distance_in_words_ago" %></small></p>
      </header>

      <%= render "notifications/shared/article_preview", json_data: json_data, notification: notification, context: "default" %>
    </div>
  <% end %>
</div>

app/views/notifications/_broadcast.html.erb
<div class="crayons-card notification notification--promoted">
  <% json_data = notification.json_data %>
  <% user = User.find_by(id: json_data["user"]["id"]) %>
  <% cache "broadcast-html-#{notification.json_data['broadcast']['title']}" do %>
    <a href="<%= json_data["user"]["path"] %>" class="crayons-avatar crayons-avatar--2xl m:crayons-avatar--3xl shrink-0 mb-4 m:mb-6">
      <img src="<%= user.profile_image_url %>" class="crayons-avatar__image" alt="link to <%= json_data["user"]["username"] %>'s profile" width="128" height="128">
    </a>
    <div class="fs-base m:fs-l broadcast-content" id="<%= sanitized_broadcast_id(json_data["broadcast"]["title"]) %>">
      <%= json_data["broadcast"]["processed_html"].html_safe %>

      <% if notification.json_data['broadcast']['type_of'] == "Welcome" %>
        <p class="fs-base pt-6 color-base-70"><%= t("views.notifications.broadcast.visit_html", settings: link_to(t("views.notifications.broadcast.settings"), user_settings_path(tab: :notifications))) %></p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/notifications/_nav_menu.html.erb
<% no_filter = params[:filter].blank? %>
<% org_filter = params[:filter].to_s.match?(/^org$/i) %>
<% comments_filter = params[:filter].to_s.match?(/^comments$/i) %>
<% user_comments = comments_filter && params[:org_id].blank? %>
<% user_posts = params[:filter].to_s.match?(/^posts$/i) && params[:org_id].blank? %>

<nav class="hidden m:block pt-4" aria-label="<%= t("views.notifications.nav.aria_label") %>">
  <div>
    <% if @organizations.present? %>
      <h3 class="crayons-subtitle-3 mb-4 pl-2"><%= @user.name %></h3>
    <% end %>

    <a
      class="crayons-link crayons-link--block <%= "crayons-link--current" if no_filter %>"
      href="<%= notifications_path %>">
      <%= t("views.notifications.nav.all") %>
    </a>
    <a
      class="crayons-link crayons-link--block <%= "crayons-link--current" if user_comments %>"
      href="<%= notifications_filter_path(:comments) %>">
      <%= t("views.notifications.nav.comments") %>
    </a>
    <a
      class="crayons-link crayons-link--block <%= "crayons-link--current" if user_posts %>"
      href="<%= notifications_filter_path(:posts) %>">
      <%= t("views.notifications.nav.posts") %>
    </a>
  </div>

  <% if @organizations.present? %>
    <% @organizations.each do |org| %>
      <div class="pt-6">
        <h3 class="crayons-subtitle-3 mb-4 pl-2"><%= org.name %></h3>
        <a
          class="crayons-link crayons-link--block <%= "crayons-link--current" if org_filter && params[:org_id].to_i == org.id %>"
          href="<%= notifications_filter_org_path(filter: :org, org_id: org.id) %>">
          <%= t("views.notifications.nav.all") %>
        </a>
        <a
          class="crayons-link crayons-link--block <%= "crayons-link--current" if comments_filter && params[:org_id].to_i == org.id %>"
          href="<%= notifications_filter_org_path(filter: :comments, org_id: org.id) %>">
          <%= t("views.notifications.nav.comments") %>
        </a>
      </div>
    <% end %>
  <% end %>
</nav>

<nav class="block m:hidden px-3" aria-label="<%= t("views.notifications.nav.aria_label") %>">
  <% if @organizations.present? %>
    <select id="notifications-filter__select" class="crayons-select mb-2">
      <option value="<%= notifications_path %>"><%= @user.name %></option>
      <% @organizations.each do |org| %>
        <option value="<%= notifications_filter_org_path(filter: :org, org_id: org.id) %>" <%= "selected" if params[:org_id].to_i == org.id %>><%= org.name %></option>
      <% end %>
    </select>
  <% end %>

  <div class="crayons-tabs <%= "hidden" if params[:org_id].present? %>">
    <ul class="crayons-tabs__list">
      <li>
        <a
          data-text="All"
          class="crayons-tabs__item <%= "crayons-tabs__item--current" if no_filter %>"
          href="<%= notifications_path %>"
          aria-current="<%= "page" if no_filter %>">
          <%= t("views.notifications.nav.all") %>
        </a>
      </li>
      <li>
        <a
          data-text="Comments"
          class="crayons-tabs__item <%= "crayons-tabs__item--current" if user_comments %>"
          href="<%= notifications_filter_path(:comments) %>"
          aria-current="<%= "page" if user_comments %>">
          <%= t("views.notifications.nav.comments") %>
        </a>
      </li>
      <li>
        <a
          data-text="Posts"
          class="crayons-tabs__item <%= "crayons-tabs__item--current" if user_posts %>"
          href="<%= notifications_filter_path(:posts) %>"
          aria-current="<%= "page" if user_posts %>">
          <%= t("views.notifications.nav.posts") %>
        </a>
      </li>
    </ul>
  </div>

  <% if @organizations.present? %>
    <% @organizations.each do |org| %>
      <div class="crayons-tabs <%= "hidden" unless params[:org_id].to_i == org.id %>">
        <a
          data-text="All"
          class="crayons-tabs__item <%= "crayons-tabs__item--current" if org_filter && params[:org_id].to_i == org.id %>"
          href="<%= notifications_filter_org_path(filter: :org, org_id: org.id) %>">
          <%= t("views.notifications.nav.all") %>
        </a>
        <a
          data-text="Comments"
          class="crayons-tabs__item <%= "crayons-tabs__item--current" if comments_filter && params[:org_id].to_i == org.id %>"
          href="<%= notifications_filter_org_path(filter: :comments, org_id: org.id) %>">
          <%= t("views.notifications.nav.comments") %>
        </a>
      </div>
    <% end %>
  <% end %>
</nav>

app/views/notifications/_reaction.html.erb
<%# missing cache key %>
<% siblings = notification.json_data["reaction"]["aggregated_siblings"].select { |n| n["created_at"] > 24.hours.ago } %>
<% if siblings.length == 0 %>
  <%= render "single_reaction", notification: notification %>
<% else %>
  <%= render "aggregated_reactions", notification: notification, siblings: siblings %>
<% end %>

app/views/notifications/index.html.erb
<% title t("views.notifications.heading") %>

<%= content_for :page_meta do %>
  <link rel="canonical" href="<%= app_url("/notifications") %>" />
  <meta name="description" content="<%= t("views.notifications.meta.description", community: community_name) %>">
  <%= meta_keywords_default %>

  <meta property="og:type" content="article" />
  <meta property="og:url" content="<%= app_url("/notifications") %>" />
  <meta property="og:title" content="<%= t("views.notifications.meta.og.title", community: community_name) %>" />
  <meta property="og:description" content="<%= t("views.notifications.meta.description", community: community_name) %>" />
  <meta property="og:site_name" content="<%= community_name %>" />

  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@<%= Settings::General.social_media_handles["twitter"] %>">
  <meta name="twitter:title" content="<%= t("views.notifications.meta.og.title", community: community_name) %>">
  <meta name="twitter:description" content="<%= t("views.notifications.meta.description", community: community_name) %>">

   <%= javascript_packs_with_chunks_tag "notificationPage", defer: true %>
<% end %>

<script>
  /**
   * A script that tracks clicks for welcome notifications.
   * The notification must have `trackNotification` as its onclick event
   * in order for this to be triggered.
   *
   * @param {Event} The click event on the notification.
   */
  function trackNotification(event) {
    const target = event.target;
    const { parentElement: { id: title }, text } = target;

    // TODO: [@forem/delightful]: This event doesn't appear to be firing on Honeybadger.
    // We probably want to remove it eventually if we continually don't see it being triggered.
    if (!title) {
      Honeybadger.notify(`Could not find parentElement.id when clicking on event target text: ${text}`);
    }

    ahoy.track("Clicked Welcome Notification", { title, text, target: target.toString() });
  }
</script>

<% if user_signed_in? %>
  <main id="main-content">
    <div class="crayons-layout crayons-layout--header-inside crayons-layout--limited-l crayons-layout--2-cols" id="notifications-container">
      <header class="crayons-page-header">
        <h1 class="crayons-title"><%= t("views.notifications.heading") %></h1>
        <a href="<%= user_settings_path(tab: :notifications) %>" class="crayons-btn crayons-btn--ghost"><%= t("views.notifications.settings") %></a>
      </header>
      <div class="crayons-layout__sidebar-left">
        <%= render "notifications/nav_menu" %>
      </div>
      <div class="crayons-layout__content" data-follow-button-container="true">
        <div id="articles-list">
          <%= render "notifications_list", params: params %>
        </div>

        <%# new or less active users that don't have a page worth of notifications
            won't be shown the "load more" button %>
        <% if @notifications.size >= @initial_page_size %>
          <button id="load-more-button" type="button" class="crayons-btn crayons-btn--secondary crayons-btn--l my-6 w-100">
            <%= t("views.notifications.load") %>
          </button>
        <% end %>
      </div>
    </div>
    <%= render "articles/fitvids" %>
  </main>
  <%= javascript_packs_with_chunks_tag "followButtons", defer: true %>
  <script>
    <%== RunkitTag.script %>
  </script>
<% else %>
  <%= render "devise/registrations/registration_form" %>
<% end %>