config/routes.rb
    confirmations: "confirmations"
  }

  devise_scope :user do
    get "/enter", to: "registrations#new", as: :sign_up
    get "/confirm-email", to: "confirmations#new"
    delete "/sign_out", to: "devise/sessions#destroy"
  end

  get "/r/mobile", to: "deep_links#mobile"
  get "/.well-known/apple-app-site-association", to: "deep_links#aasa"

  scope "(/locale/:locale)", defaults: { locale: nil } do
    get "/locale/:locale", to: "stories#index"

    draw :admin

    constraints(->(_req) { Listing.feature_enabled? }) do
      draw :listing
    end

    namespace :stories, defaults: { format: "json" } do
      resource :feed, only: [:show] do
        resource :pinned_article, only: %w[show update destroy]

        get ":timeframe", to: "feeds#show", as: :timeframe
      end
    end

    namespace :api, defaults: { format: "json" } do
      scope module: :v1, constraints: ApiConstraints.new(version: 1, default: false) do
        put "/users/:id/suspend", to: "users#suspend", as: :user_suspend
        put "/articles/:id/unpublish", to: "articles#unpublish", as: :article_unpublish
        put "/users/:id/unpublish", to: "users#unpublish", as: :user_unpublish

        post "/reactions", to: "reactions#create"
        post "/reactions/toggle", to: "reactions#toggle"

        draw :api
      end

      scope module: :v0, constraints: ApiConstraints.new(version: 0, default: true) do
        draw :api
      end
    end

    namespace :notifications do
      resources :counts, only: [:index]
      resources :reads, only: [:create]
    end

    namespace :incoming_webhooks do
      get "/mailchimp/:secret/unsubscribe", to: "mailchimp_unsubscribes#index", as: :mailchimp_unsubscribe_check
      post "/mailchimp/:secret/unsubscribe", to: "mailchimp_unsubscribes#create", as: :mailchimp_unsubscribe
    end

    resources :messages, only: [:create]
    resources :articles, only: %i[update create destroy] do
      patch "/admin_unpublish", to: "articles#admin_unpublish"
      patch "/admin_featured_toggle", to: "articles#admin_featured_toggle"
    end
    resources :article_mutes, only: %i[update]
    resources :comments, only: %i[create update destroy] do
      patch "/hide", to: "comments#hide"
      patch "/unhide", to: "comments#unhide"
      patch "/admin_delete", to: "comments#admin_delete"
      collection do
        post "/moderator_create", to: "comments#moderator_create"
      end
    end
    resources :comment_mutes, only: %i[update]
    resources :users, only: %i[index], defaults: { format: :json } do # internal API
      collection do
        resources :devices, only: %i[create destroy]
      end
    end
    namespace :users do
      resource :settings, only: %i[update]
      resource :notification_settings, only: %i[update]
    end
    resources :users, only: %i[update]
    resources :reactions, only: %i[index create]
    resources :response_templates, only: %i[index create edit update destroy]
    resources :feedback_messages, only: %i[index create]
    resources :organizations, only: %i[update create destroy]
    resources :follows, only: %i[show create] do
      collection do
        get "/bulk_show", to: "follows#bulk_show"
        patch "/bulk_update", to: "follows#bulk_update"
      end
    end
    resources :image_uploads, only: [:create]
    resources :notifications, only: [:index]
    resources :tags, only: [:index] do
      collection do
        get "/onboarding", to: "tags#onboarding"
        get "/suggest", to: "tags#suggest", defaults: { format: :json }
        get "/bulk", to: "tags#bulk", defaults: { format: :json }
      end
    end
    resources :stripe_active_cards, only: %i[create update destroy]
    resources :github_repos, only: %i[index] do
      collection do
        post "/update_or_create", to: "github_repos#update_or_create"
      end
    end
    resources :videos, only: %i[index create new]
    resources :video_states, only: [:create]
    resources :twilio_tokens, only: [:show]
    resources :tag_adjustments, only: %i[create destroy]
    resources :rating_votes, only: [:create]
    resources :page_views, only: %i[create update]
    resources :credits, only: %i[index new create] do
      get "purchase", on: :collection, to: "credits#new"
    end
    resources :reading_list_items, only: [:update]
    resources :poll_votes, only: %i[show create]
    resources :poll_skips, only: [:create]
    resources :profile_pins, only: %i[create update]
    resources :display_ad_events, only: [:create]
    resources :badges, only: [:index]
    resources :user_blocks, param: :blocked_id, only: %i[show create destroy]
    resources :podcasts, only: %i[new create]
    resources :article_approvals, only: %i[create]
    resources :sidebars, only: %i[show]
    resources :profile_preview_cards, only: %i[show]
    resources :user_subscriptions, only: %i[create] do
      collection do
        get "/subscribed", action: "subscribed"
      end
    end
    namespace :followings, defaults: { format: :json } do
      get :users
      get :tags
      get :organizations
      get :podcasts
    end

    scope module: "users" do
      resource :onboarding, only: %i[show update]
      patch "/onboarding_checkbox_update", to: "onboardings#onboarding_checkbox_update"
    end

    resources :profiles, only: %i[update]
    resources :profile_field_groups, only: %i[index], defaults: { format: :json }

    resources :liquid_tags, only: %i[index], defaults: { format: :json }

    resources :discussion_locks, only: %i[create destroy]

    get "/verify_email_ownership", to: "email_authorizations#verify", as: :verify_email_authorizations
    get "/search/tags", to: "search#tags"
    get "/search/usernames", to: "search#usernames"
    get "/search/feed_content", to: "search#feed_content"
    get "/search/reactions", to: "search#reactions"
    get "/notifications/:filter", to: "notifications#index", as: :notifications_filter
    get "/notifications/:filter/:org_id", to: "notifications#index", as: :notifications_filter_org
    get "/notification_subscriptions/:notifiable_type/:notifiable_id", to: "notification_subscriptions#show"
    post "/notification_subscriptions/:notifiable_type/:notifiable_id", to: "notification_subscriptions#upsert"
    patch "/onboarding_notifications_checkbox_update",
          to: "users/notification_settings#onboarding_notifications_checkbox_update"
    get "email_subscriptions/unsubscribe"

    get "/internal", to: redirect("/admin")
    get "/internal/:path", to: redirect("/admin/%{path}")

    get "/social_previews/article/:id", to: "social_previews#article", as: :article_social_preview

    get "/async_info/base_data", controller: "async_info#base_data", defaults: { format: :json }

    post "users/join_org", to: "users#join_org"
    post "users/leave_org/:organization_id", to: "users#leave_org", as: :users_leave_org
    post "users/add_org_admin", to: "users#add_org_admin"
    post "users/remove_org_admin", to: "users#remove_org_admin"
    post "users/remove_from_org", to: "users#remove_from_org"
    delete "users/remove_identity", to: "users#remove_identity"
    post "users/request_destroy", to: "users#request_destroy", as: :user_request_destroy
    get "users/confirm_destroy/:token", to: "users#confirm_destroy", as: :user_confirm_destroy
    delete "users/full_delete", to: "users#full_delete", as: :user_full_delete
    post "organizations/generate_new_secret", to: "organizations#generate_new_secret"
    post "users/api_secrets", to: "api_secrets#create", as: :users_api_secrets
    delete "users/api_secrets/:id", to: "api_secrets#destroy", as: :users_api_secret
    post "users/update_password", to: "users#update_password", as: :user_update_password

    get "/robots.:format", to: "pages#robots"
    get "/api", to: redirect("https://developers.forem.com/api")
    get "/privacy", to: "pages#privacy"
    get "/terms", to: "pages#terms"
    get "/contact", to: "pages#contact"
    get "/code-of-conduct", to: "pages#code_of_conduct"
    get "/report-abuse", to: "pages#report_abuse"
    get "/welcome", to: "pages#welcome"
    get "/challenge", to: "pages#challenge"
    get "/checkin", to: "pages#checkin"
    get "/💸", to: redirect("t/hiring")
    get "/survey", to: redirect("https://dev.to/ben/final-thoughts-on-the-state-of-the-web-survey-44nn")
    get "/search", to: "stories/articles_search#index"
    post "articles/preview", to: "articles#preview"
    post "comments/preview", to: "comments#preview"

    get "/about", to: "pages#about"
    get "/security", to: "pages#bounty"
    get "/community-moderation", to: "pages#community_moderation"
    get "/faq", to: "pages#faq"
    get "/page/post-a-job", to: "pages#post_a_job"
    get "/tag-moderation", to: "pages#tag_moderation"

    get "/mod", to: "moderations#index", as: :mod
    get "/mod/:tag", to: "moderations#index"

    post "/fallback_activity_recorder", to: "ga_events#create"

    get "/page/:slug", to: "pages#show"

    scope "p" do
      pages_actions = %w[welcome editor_guide publishing_from_rss_guide markdown_basics].freeze
      pages_actions.each do |action|
        get action, action: action, controller: "pages"
      end
    end

    get "/settings/integrations", to: redirect("/settings/extensions")
    get "/settings/misc", to: redirect("/settings")
    get "/settings/publishing-from-rss", to: redirect("/settings/extensions")
    get "/settings/ux", to: redirect("/settings/customization")

    get "/settings/(:tab)", to: "users#edit", as: :user_settings
    get "/settings/:tab/:org_id", to: "users#edit", constraints: { tab: /organization/ }
    get "/settings/:tab/:id", to: "users#edit", constraints: { tab: /response-templates/ }
    get "/signout_confirm", to: "users#signout_confirm"
    get "/dashboard", to: "dashboards#show"
    get "/dashboard/analytics", to: "dashboards#analytics"
    get "dashboard/analytics/org/:org_id", to: "dashboards#analytics", as: :dashboard_analytics_org

app/controllers/admin/tags/moderators_controller.rb
module Admin
  module Tags
    class ModeratorsController < Admin::ApplicationController
      def authorization_resource
        Tag
      end

      after_action only: %i[create destroy] do
        Audit::Logger.log(:moderator, current_user, params.dup)
      end

      def create
        user = User.find_by(id: tag_params[:user_id])
        unless user
          flash[:error] =
            I18n.t("errors.messages.general",
                   errors: I18n.t("admin.tags.moderators_controller.not_found", user_id: tag_params[:user_id]))
          return redirect_to edit_admin_tag_path(params[:tag_id])
        end

        notification_setting = user.notification_setting
        if notification_setting.update(email_tag_mod_newsletter: true)
          TagModerators::Add.call([user.id], [params[:tag_id]])
          flash[:success] =
            I18n.t("admin.tags.moderators_controller.added", username: user.username)
        else
          flash[:error] = I18n.t("errors.messages.general", errors:
            I18n.t("admin.tags.moderators_controller.not_found_or",
                   user_id: tag_params[:user_id],
                   errors: notification_setting.errors_as_sentence))
        end
        redirect_to edit_admin_tag_path(params[:tag_id])
      end

      def destroy
        user = User.find_by(id: tag_params[:user_id])
        unless user
          flash[:error] = "Error: User ID ##{tag_params[:user_id]} was not found"
          return redirect_to edit_admin_tag_path(params[:tag_id])
        end

        notification_setting = user.notification_setting
        tag = Tag.find_by(id: params[:tag_id])
        if notification_setting.update(email_tag_mod_newsletter: false)
          TagModerators::Remove.call(user, tag)
          flash[:success] =
            I18n.t("admin.tags.moderators_controller.removed", username: user.username,
                                                               user_id: user.id)
        else
          flash[:error] = I18n.t("errors.messages.general", errors:
            I18n.t("admin.tags.moderators_controller.not_found_or",
                   user_id: tag_params[:user_id],
                   errors: notification_setting.errors_as_sentence))
        end
        redirect_to edit_admin_tag_path(tag.id)
      end

      private

      def tag_params
        params.require(:tag).permit(:user_id)
      end
    end
  end
end

app/controllers/admin/tags_controller.rb
module Admin
  class TagsController < Admin::ApplicationController
    layout "admin"

    ALLOWED_PARAMS = %i[
      id supported rules_markdown short_summary pretty_name bg_color_hex
      text_color_hex user_id alias_for badge_id requires_approval
      social_preview_template wiki_body_markdown submission_template
    ].freeze

    before_action :set_default_options, only: %i[index]
    before_action :badges_for_options, only: %i[new create edit update]
    after_action only: [:update] do
      Audit::Logger.log(:moderator, current_user, params.dup)
    end

    def index
      @q = Tag.ransack(params[:q])
      @tags = @q.result.page(params[:page]).per(50)
    end

    def new
      @tag = Tag.new
    end

    def create
      @tag = Tag.new(tag_params)
      @tag.name = params[:tag][:name].downcase

      if @tag.save
        flash[:success] = I18n.t("admin.tags_controller.created", tag_name: @tag.name)
        redirect_to edit_admin_tag_path(@tag)
      else
        flash[:danger] = @tag.errors_as_sentence
        render :new
      end
    end

    def edit
      @tag = Tag.find(params[:id])
      @tag_moderators = User.with_role(:tag_moderator, @tag).select(:id, :username)
    end

    def update
      @tag = Tag.find(params[:id])
      if @tag.update(tag_params)
        ::Tags::AliasRetagWorker.perform_async(@tag.id) if tag_alias_updated?
        flash[:success] = I18n.t("admin.tags_controller.updated", tag_name: @tag.name)
      else
        flash[:error] =
          I18n.t("admin.tags_controller.update_fail", errors: @tag.errors_as_sentence)
      end
      redirect_to edit_admin_tag_path(@tag.id)
    end

    private

    def set_default_options
      params[:q] = { supported_not_null: "true" } if params[:q].blank?
      params[:q][:s] = "taggings_count desc" if params[:q][:s].blank?
    end

    def badges_for_options
      @badges_for_options = Badge.pluck(:title, :id)
    end

    def tag_params
      params.require(:tag).permit(ALLOWED_PARAMS)
    end

    def tag_alias_updated?
      tag_params[:alias_for].present?
    end
  end
end

app/controllers/api/v0/tags_controller.rb
module Api
  module V0
    class TagsController < ApiController
      include Api::TagsController

      before_action :set_cache_control_headers, only: %i[index]
    end
  end
end

app/controllers/api/v1/tags_controller.rb
module Api
  module V1
    class TagsController < ApiController
      include Api::TagsController

      before_action :set_cache_control_headers, only: %i[index]
    end
  end
end

app/controllers/concerns/api/tags_controller.rb
module Api
  module TagsController
    extend ActiveSupport::Concern

    ATTRIBUTES_FOR_SERIALIZATION = %i[id name bg_color_hex text_color_hex].freeze
    private_constant :ATTRIBUTES_FOR_SERIALIZATION

    def index
      page = params[:page]
      per_page = (params[:per_page] || 10).to_i
      per_page_max = (ApplicationConfig["API_PER_PAGE_MAX"] || 1000).to_i
      num = [per_page, per_page_max].min

      @tags = Tag.select(ATTRIBUTES_FOR_SERIALIZATION)
        .order(taggings_count: :desc)
        .page(page).per(num)

      set_surrogate_key_header Tag.table_key, @tags.map(&:record_key)
    end
  end
end

app/views/tags/_liquid.html.erb
<div class="ltag__tag ltag__tag__id__<%= tag.id %>" style="border-color:<%= dark_color %>;box-shadow: 3px 3px 0px <%= dark_color %>;">
    <div class="ltag__tag__content">
      <h2>#<a href="<%= URL.tag tag %>" class="ltag__tag__link"><%= tag.name %></a> <%= follow_button(tag, "full", "c-btn--secondary fs-base") %></h2>
      <div class="ltag__tag__summary">
        <%= tag.short_summary %>
      </div>
    </div>
</div>

app/views/tags/edit.html.erb
<% title t("views.tags.edit.meta.title", tag: @tag.name) %>

<main id="main-content" class="crayons-layout crayons-layout--limited-m">
  <header class="crayons-card flex items-center justify-between branded-4 p-3 pr-1 m:pr-5 m:p-6 m:pt-5" style="border-top-color: <%= @tag.bg_color_hex %>">
    <h1 class="crayons-title">
      <span class="opacity-50">#</span><%= @tag.accessible_name %>
    </h1>
    <div class="flex">
      <% if current_user.any_admin? %>
        <a href="<%= edit_admin_tag_path(@tag.id) %>" class="crayons-btn crayons-btn--ghost" data-no-instant><%= t("views.tags.edit.admin") %></a>
      <% end %>
      <a target="_blank" rel="noopener" href="https://admin.forem.com/docs/forem-basics/tags#editing-a-tag" class="crayons-btn crayons-btn--ghost"><%= t("views.tags.edit.help") %></a>
      <a href="/t/<%= @tag %>" class="crayons-btn crayons-btn--ghost"><%= t("views.tags.edit.view") %></a>
    </div>
  </header>

  <%= form_tag("/tag/#{@tag.id}", method: :patch, class: "crayons-card p-4 m:p-6 grid gap-4") do %>
    <% if flash[:success] %>
      <div class="crayons-notice crayons-notice--success">
        <%= flash[:success] %>
      </div>
    <% elsif flash[:error] %>
      <div class="crayons-notice crayons-notice--danger">
        <ul>
          <% flash[:error].each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <% label_i18n = ->(param) { label_tag param, t("views.tags.edit.form.#{param}.label") } %>
    <div class="crayons-field">
      <%= label_tag :pretty_name, nil, class: "crayons-field__label" %>
      <%= text_field_tag "tag[pretty_name]", @tag.pretty_name, placeholder: t("views.tags.edit.form.pretty_name.placeholder"), class: "crayons-textfield" %>
    </div>
    <div class="flex gap-4">
      <div class="crayons-field flex-1">
        <%= label_tag :tag_bg_color_hex, I18n.t("views.tags.edit.form.bg_color_hex.label"), class: "crayons-field__label" %>
        <%= text_field_tag "tag[bg_color_hex]", @tag.bg_color_hex.presence || "#000000", placeholder: "#000000", class: "crayons-textfield", data: { color_picker: true, label_text: I18n.t("views.tags.edit.form.bg_color_hex.label") } %>
      </div>
    </div>
    <div class="crayons-field">
      <%= label_tag :short_summary, nil, class: "crayons-field__label" %>
      <%= text_area_tag "tag[short_summary]", @tag.short_summary, placeholder: t("views.tags.edit.form.short_summary.placeholder"), class: "crayons-textfield" %>
    </div>
    <div class="crayons-field">
      <%= label_tag :wiki_body_markdown, nil, class: "crayons-field__label" %>
      <%= text_area_tag "tag[wiki_body_markdown]", @tag.wiki_body_markdown, placeholder: t("views.tags.edit.form.wiki_body_markdown.placeholder"), class: "crayons-textfield" %>
    </div>
    <div class="crayons-field">
      <%= label_tag :rules_markdown, nil, class: "crayons-field__label" %>
      <%= text_area_tag "tag[rules_markdown]", @tag.rules_markdown, placeholder: t("views.tags.edit.form.rules_markdown.placeholder"), class: "crayons-textfield" %>
    </div>
    <div>
      <%= submit_tag t("views.tags.edit.form.submit"), class: "crayons-btn" %>
    </div>
  <% end %>
</main>
<%= javascript_packs_with_chunks_tag "enhanceColorPickers", defer: true %>

app/views/tags/index.html.erb
<% title t("views.tags.meta.title") %>

<%= content_for :page_meta do %>
  <link rel="canonical" href="<%= app_url("/tags") %>" />
  <meta name="description" content="<%= t("views.tags.meta.description", community: community_name) %>">
  <%= meta_keywords_default %>

  <meta property="og:type" content="article" />
  <meta property="og:url" content="<%= app_url("/tags") %>" />
  <meta property="og:title" content="<%= t("views.tags.meta.description", community: community_name) %>" />
  <meta property="og:image" content="<%= Settings::General.main_social_image %>" />
  <meta property="og:description" content="<%= t("views.tags.meta.og.description", community: community_name) %>" />
  <meta property="og:site_name" content="<%= community_name %>" />

  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@<%= Settings::General.social_media_handles["twitter"] %>">
  <meta name="twitter:title" content="<%= t("views.tags.meta.description", community: community_name) %>">
  <meta name="twitter:description" content="<%= t("views.tags.meta.og.description", community: community_name) %>">
  <meta name="twitter:image:src" content="<%= Settings::General.main_social_image %>">
<% end %>

<main id="main-content" class="crayons-layout crayons-layout--header-inside">
  <header class="crayons-page-header">
    <h1 class="crayons-title">
      <% if params[:q].present? %>
        <%= t("views.tags.heading.search_results", q: params[:q]) %>
      <% else %>
        <%= t("views.tags.heading.default") %>
      <% end %>
    </h1>
    <form accept-charset="UTF-8" method="get" action="<%= tags_path %>" role="search">
      <div class="crayons-fields crayons-fields--horizontal">
        <div class="crayons-field flex-1 relative">
          <input class="crayons-header--search-input crayons-textfield js-search-input" type="text" id="nav-search" aria-label="<%= t("views.tags.search.aria_labels.search_input") %>" name="q" placeholder="<%= t("views.tags.search.placeholder") %>" autocomplete="off" />
          <button type="submit" aria-label="<%= t("views.tags.search.aria_labels.submit") %>" class="c-btn c-btn--icon-alone absolute inset-px left-auto mt-0 py-0">
            <%= crayons_icon_tag(:search, aria_hidden: true, title: t("views.search.icon.title")) %>
          </button>
        </div>
          <%= link_to t("views.tags.following_tags"), dashboard_following_tags_path, class: "crayons-btn crayons-btn--ghost" %>
      </div>
    </form>
  </header>
  <% if @tags.empty? %>
    <div class="articles-list crayons-layout__content" id="articles-list" data-follow-button-container="true">
      <div id="banner-section"></div>
      <div class="substories search-results-loaded" id="substories"><div class="p-9 align-center crayons-card">No results match that query</div></div>
    </div>
  <% else %>
    <div class="grid gap-3 m:gap-4 l:gap-6 m:grid-cols-2 l:grid-cols-3 px-3 m:px-0 pb-3" data-follow-button-container="true">
      <% @tags.each do |tag| %>
        <div class="tag-card crayons-card branded-4 p-3 pt-2 m:p-6 m:pt-4 relative" style="border-top-color: <%= tag.bg_color_hex %>; ">
          <h3 class="mb-1 -ml-2">
            <%= render_tag_link(tag.accessible_name) %>
          </h3>
          <% if tag.short_summary.present? %>
            <p class="mb-2 color-base-70 truncate-at-3"><%= sanitize tag.short_summary %></p>
          <% end %>
          <p class="mb-3 fs-s color-base-60">
            <%= t("views.tags.published", count: tag.taggings_count) %>
          </p>

          <% if tag %>
            <div class="mt-auto">
              <button
                class="crayons-btn crayons-btn--secondary follow-action-button"
                data-info='<%= DataInfo.to_json(object: tag, class_name: "Tag", followStyle: "secondary") %>'>
                <%= t("views.tags.follow") %>
              </button>
            </div>
          <% end %>

          <% if tag.badge_id && tag.badge %>
            <img src="<%= optimized_image_url(tag.badge.badge_image_url, width: 180) %>" style="width: 64px; height: 64px; transform: rotate(<%= -25 + (tag.id.digits.first * 5) %>deg);" class="right-1 bottom-1 absolute" alt="" loading="lazy" />
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</main>
<%= javascript_packs_with_chunks_tag "followButtons", defer: true %>